-- Drop tables if they exist
DROP TABLE IF EXISTS prices;
DROP TABLE IF EXISTS brand;

-- Create the "brand" table
CREATE TABLE brand (
                       brand_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                       name VARCHAR(255),
                       PRIMARY KEY (brand_id)
);

-- Create the "prices" table
CREATE TABLE prices (
                        curr VARCHAR(7),
                        discount NUMERIC(38,2),
                        price NUMERIC(38,2),
                        price_list INTEGER,
                        priority INTEGER,
                        tax_rate NUMERIC(38,2),
                        brand_id BIGINT,
                        end_date TIMESTAMP(6),
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY,
                        product_id BIGINT,
                        start_date TIMESTAMP(6),
                        PRIMARY KEY (id)
);

-- Add foreign key constraint
ALTER TABLE prices
    ADD CONSTRAINT FK8kmllaucc5kqo34i4pjioyjxl
        FOREIGN KEY (brand_id) REFERENCES brand (brand_id);

INSERT INTO brand (brand_id, name) VALUES (1, 'ZARA'), (2, 'Bershka'), (3, 'Pull&Bear');
INSERT INTO prices (curr, discount, price, price_list, priority, tax_rate, brand_id, end_date, product_id, start_date)
VALUES ('EUR', 10.15, 35.50, 1, 0, 1.5, 1, '2020-12-31 23:59:59.000000', 35455, '2020-06-14 00:00:00.000000'),
       ('EUR', 20.15, 25.45, 1, 1, 2.5, 1, '2020-06-14 18:30:00.000000', 35455, '2020-06-14 15:00:00.000000'),
       ('EUR', 05.50, 30.50, 1, 1, 1.5, 1, '2020-06-15 11:00:00.000000', 35455, '2020-06-15 00:00:00.000000'),
       ('EUR', 10.00, 38.95, 1, 1, 2.5, 1, '2020-12-31 23:59:59.000000', 35455, '2020-06-14 16:00:00.000000');

